version: '3'
services:
  consde:
    container_name: consde
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run serve"
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    - /app/node_modules